### ISSUE TITLE
Slides about LLM and KG

### ISSUE THREAD

**Issue by nuochenpku** [guangchen811/guangchen811.github.io#1]
Hi, 
 I find you will have a talk "大语言模型与知识图谱的相互促进"， I am very interested in this, could you please share the sildes?

Thanks, sincerely!

**Comment by guangchen811** [comment]
Hi Jerry,

I would be happy to share the slides with you, but at the moment, they are still undergoing revisions and have a few issues that need to be addressed. So, I may need to send them to you after the revision is completed, and I will also update the corresponding topic on this blog.

Besides, I have to say that my knowledge of the knowledge graph is still limited, and I may not provide you the information that you are expecting. If that is the case, I apologize for the inconvenience.

Best regards.

**Comment by guangchen811** [comment]
I have already sent the slides to the email address displayed in your Google Scholar profile. Please let me know if you are no longer using that email address.

**Comment by guangchen811** [comment]
I have already sent an email regarding the issue and it will be closed.
